version: "3.2"
services:
  localstack:
    image: localstack/localstack
    container_name: api_gateway_integration
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8085:8080"
      # - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8085
      - START_WEB=1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      # - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"
